@echo off
cd /d %~dp0
set OPENAI_API_KEY=
set LLM_API_KEY=
set OPENAI_MODEL=
set LLM_MODEL=
set OPENAI_BASE_URL=
set LLM_BASE_URL=
set TELEGRAM_BOT_TOKEN=
set VCLAW_TELEGRAM_BOT_TOKEN=
set ALLOWED_TELEGRAM_USER_ID=
set VCLAW_TELEGRAM_ALLOWED_USER_IDS=
set DATABASE_URL=
set VCLAW_GOOGLE_CREDENTIALS_PATH=
set VCLAW_GOOGLE_TOKEN_PATH=
set VCLAW_GOOGLE_TOOLS_MODE=
set VCLAW_WEB_TOOLS_MODE=
set TAVILY_API_KEY=
set TALIVY_API_KEY=
set TAVILY_BASE_URL=
set VCLAW_SANDBOX_IMAGE=
set VCLAW_SANDBOX_WORKSPACE_DIR=
set VCLAW_SKILL_CACHE_DIR=
set VCLAW_SKILL_NUDGE_INTERVAL=
set VCLAW_PARALLEL_ENABLED=
set VCLAW_PARALLEL_MAX_WORKERS=
set VCLAW_PARALLEL_TOOL_TIMEOUT=
set METRICS_PORT=
set LANGFUSE_PUBLIC_KEY=
set LANGFUSE_SECRET_KEY=
set LANGFUSE_HOST=
set LANGFUSE_PROJECT_ID=
vclaw.exe google auth
pause
