package main

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

var setupInput io.Reader = os.Stdin

const defaultDotEnvTemplate = `# V-Claw local environment.
# Generated by vclaw setup. Never commit real tokens.

OPENAI_API_KEY=
OPENAI_MODEL=gpt-5.4-mini
OPENAI_BASE_URL=
VCLAW_COMPACTOR_MODEL=gpt-4o-mini
VCLAW_TIMEZONE=Asia/Ho_Chi_Minh

TELEGRAM_BOT_TOKEN=
ALLOWED_TELEGRAM_USER_ID=
DATA_DIR=./data
LOG_DIR=./logs

VCLAW_SKILL_NUDGE_INTERVAL=0
VCLAW_GOOGLE_CREDENTIALS_PATH=configs/google/credentials.json
VCLAW_GOOGLE_TOKEN_PATH=configs/google/token.json
VCLAW_GOOGLE_TOOLS_MODE=auto
VCLAW_WEB_TOOLS_MODE=auto
TAVILY_API_KEY=
`

func runSetup() error {
	if _, err := os.Stat(defaultEnvPath); err != nil {
		if !errors.Is(err, os.ErrNotExist) {
			return err
		}
		createdFrom, err := createDefaultDotEnv(defaultEnvPath)
		if err != nil {
			return err
		}
		fmt.Printf("Created .env from %s\n", createdFrom)
	}

	file, err := readDotEnvFile(defaultEnvPath)
	if err != nil {
		return err
	}
	reader := bufio.NewReader(setupInput)
	updates := map[string]string{}
	for _, key := range []string{"OPENAI_API_KEY", "TELEGRAM_BOT_TOKEN", "ALLOWED_TELEGRAM_USER_ID"} {
		value, changed, err := promptEnvValue(reader, file.values[key], key, key == "ALLOWED_TELEGRAM_USER_ID")
		if err != nil {
			return err
		}
		if changed {
			updates[key] = value
		}
	}
	for key, value := range map[string]string{
		"VCLAW_SKILL_NUDGE_INTERVAL": "0",
		"VCLAW_GOOGLE_TOOLS_MODE":    "auto",
		"VCLAW_WEB_TOOLS_MODE":       "auto",
	} {
		if strings.TrimSpace(file.values[key]) == "" {
			updates[key] = value
		}
	}
	if len(updates) > 0 {
		if err := updateDotEnvFile(defaultEnvPath, file.lines, updates); err != nil {
			return err
		}
		fmt.Println("Updated .env")
	} else {
		fmt.Println("No .env changes needed")
	}
	fmt.Println()
	fmt.Println("Next commands:")
	fmt.Println("  vclaw google auth   # optional, enables Google tools")
	fmt.Println("  vclaw doctor")
	fmt.Println("  vclaw start")
	return nil
}

func runDoctor(path string) error {
	failures := []string{}
	warnings := []string{}
	if _, err := os.Stat(path); err != nil {
		if errors.Is(err, os.ErrNotExist) {
			warnings = append(warnings, ".env is missing; shell env may still provide values")
		} else {
			failures = append(failures, fmt.Sprintf(".env cannot be read: %v", err))
		}
	} else if err := loadDotEnv(path); err != nil {
		failures = append(failures, fmt.Sprintf(".env exists but cannot be parsed: %v", err))
	}

	if strings.TrimSpace(envFirst("OPENAI_API_KEY", "LLM_API_KEY")) == "" {
		failures = append(failures, "OPENAI_API_KEY is missing")
	}
	if strings.TrimSpace(envFirst("TELEGRAM_BOT_TOKEN", "VCLAW_TELEGRAM_BOT_TOKEN")) == "" {
		failures = append(failures, "TELEGRAM_BOT_TOKEN is missing")
	}
	allowedUser := firstCSV(envFirst("ALLOWED_TELEGRAM_USER_ID", "VCLAW_TELEGRAM_ALLOWED_USER_IDS"))
	if strings.TrimSpace(allowedUser) == "" {
		failures = append(failures, "ALLOWED_TELEGRAM_USER_ID is missing")
	} else if !isDigits(allowedUser) {
		failures = append(failures, "ALLOWED_TELEGRAM_USER_ID must be numeric")
	}
	if envOrDefault("VCLAW_SKILL_NUDGE_INTERVAL", "") != "0" {
		failures = append(failures, "VCLAW_SKILL_NUDGE_INTERVAL must be 0 for release config")
	}

	googleMode := envOrDefault("VCLAW_GOOGLE_TOOLS_MODE", appToolModeAuto())
	googleReady := doctorFileExists(envOrDefault("VCLAW_GOOGLE_CREDENTIALS_PATH", defaultCredentialsPath)) && doctorFileExists(envOrDefault("VCLAW_GOOGLE_TOKEN_PATH", defaultTokenPath))
	if !googleReady {
		switch googleMode {
		case "required":
			failures = append(failures, "Google credentials/token missing while VCLAW_GOOGLE_TOOLS_MODE=required")
		case "auto", "off":
			warnings = append(warnings, fmt.Sprintf("Google credentials/token missing while Google mode is %s", googleMode))
		}
	}
	webMode := envOrDefault("VCLAW_WEB_TOOLS_MODE", appToolModeAuto())
	if strings.TrimSpace(envFirst("TAVILY_API_KEY")) == "" {
		switch webMode {
		case "required":
			failures = append(failures, "TAVILY_API_KEY is missing while VCLAW_WEB_TOOLS_MODE=required")
		case "auto":
			warnings = append(warnings, "Web tools unavailable because TAVILY_API_KEY is missing while web mode is auto")
		}
	}
	if !doctorFileExists(filepath.Join("dist", "vclaw-windows-amd64.zip")) {
		warnings = append(warnings, "Release ZIP missing before packaging")
	}

	fmt.Println("V-Claw doctor")
	printDoctorList("Blockers", failures)
	printDoctorList("Warnings", warnings)
	if len(failures) > 0 {
		return fmt.Errorf("doctor found %d blocker(s)", len(failures))
	}
	fmt.Println("Doctor passed.")
	return nil
}

func appToolModeAuto() string { return "auto" }

type dotEnvFile struct {
	lines  []string
	values map[string]string
}

func readDotEnvFile(path string) (dotEnvFile, error) {
	bytes, err := os.ReadFile(path)
	if err != nil {
		return dotEnvFile{}, err
	}
	lines := strings.Split(strings.ReplaceAll(string(bytes), "\r\n", "\n"), "\n")
	if len(lines) > 0 && lines[len(lines)-1] == "" {
		lines = lines[:len(lines)-1]
	}
	values := map[string]string{}
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		key, value, ok := strings.Cut(trimmed, "=")
		if ok {
			values[strings.TrimSpace(key)] = parseDotEnvValue(strings.TrimSpace(value))
		}
	}
	return dotEnvFile{lines: lines, values: values}, nil
}

func promptEnvValue(reader *bufio.Reader, existing string, key string, numeric bool) (string, bool, error) {
	if strings.TrimSpace(existing) != "" {
		fmt.Printf("%s is set (%s). Overwrite? [y/N]: ", key, maskSecret(existing))
		answer, err := readSetupLine(reader)
		if err != nil {
			return "", false, err
		}
		if strings.ToLower(strings.TrimSpace(answer)) != "y" {
			return "", false, nil
		}
	}
	for {
		fmt.Printf("Enter %s: ", key)
		value, err := readSetupLine(reader)
		if err != nil {
			return "", false, err
		}
		value = strings.TrimSpace(value)
		if value == "" {
			return "", false, nil
		}
		if numeric && !isDigits(value) {
			fmt.Println("ALLOWED_TELEGRAM_USER_ID must be numeric.")
			continue
		}
		return value, true, nil
	}
}

func readSetupLine(reader *bufio.Reader) (string, error) {
	line, err := reader.ReadString('\n')
	if err != nil && !errors.Is(err, io.EOF) {
		return "", err
	}
	return strings.TrimPrefix(strings.TrimRight(line, "\r\n"), "\ufeff"), nil
}

func updateDotEnvFile(path string, lines []string, updates map[string]string) error {
	seen := map[string]bool{}
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		key, _, ok := strings.Cut(trimmed, "=")
		if !ok {
			continue
		}
		key = strings.TrimSpace(key)
		if value, exists := updates[key]; exists {
			lines[i] = key + "=" + value
			seen[key] = true
		}
	}
	for key, value := range updates {
		if !seen[key] {
			lines = append(lines, key+"="+value)
		}
	}
	return os.WriteFile(path, []byte(strings.Join(lines, "\n")+"\n"), 0600)
}

func createDefaultDotEnv(path string) (string, error) {
	if err := copyFile(".env.example", path); err == nil {
		return ".env.example", nil
	} else if !errors.Is(err, os.ErrNotExist) {
		return "", fmt.Errorf("create .env from .env.example: %w", err)
	}
	if err := os.WriteFile(path, []byte(defaultDotEnvTemplate), 0600); err != nil {
		return "", fmt.Errorf("create .env from built-in template: %w", err)
	}
	return "built-in template", nil
}

func copyFile(src string, dst string) error {
	bytes, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	return os.WriteFile(dst, bytes, 0600)
}

func isDigits(value string) bool {
	if value == "" {
		return false
	}
	for _, r := range value {
		if r < '0' || r > '9' {
			return false
		}
	}
	return true
}

func maskSecret(value string) string {
	value = strings.TrimSpace(value)
	if len(value) <= 4 {
		return "****"
	}
	return value[:2] + "****" + value[len(value)-2:]
}

func doctorFileExists(path string) bool {
	if strings.TrimSpace(path) == "" {
		return false
	}
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}

func printDoctorList(title string, items []string) {
	fmt.Println(title + ":")
	if len(items) == 0 {
		fmt.Println("  none")
		return
	}
	for _, item := range items {
		fmt.Println("  - " + item)
	}
}
